#!/usr/bin/env python3
"""
SAC 2026 — Generate CompScript import properties from volunteer data.

Reads volunteers.json (output of extract_volunteers.py) and generates
properties that can be set in CompScript, including:
  - Scramble capabilities per event
  - Role preferences (judge/scrambler/runner scores)
  - Score taker candidates
  - Available days

Usage:
    cd wca/
    uv run scc-scripts/2026-sac/data/extract_volunteers.py   # first
    uv run scc-scripts/2026-sac/data/generate_import.py       # then

Output:
    scc-scripts/2026-sac/data/volunteer_properties.cs
    scc-scripts/2026-sac/data/score_takers.txt
    scc-scripts/2026-sac/data/scramble_report.txt
"""

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
INPUT_FILE = SCRIPT_DIR / "volunteers.json"
OUTPUT_CS = SCRIPT_DIR / "volunteer_properties.cs"
OUTPUT_SCORE_TAKERS = SCRIPT_DIR / "score_takers.txt"
OUTPUT_SCRAMBLE = SCRIPT_DIR / "scramble_report.txt"


def normalize_wca_id_for_cs(wca_id: str | None) -> str | None:
    """Convert WCA ID to CompScript format (uppercase, no special chars)."""
    if not wca_id:
        return None
    clean = wca_id.strip().upper()
    if len(clean) == 10 and clean[:4].isdigit() and clean[-2:].isdigit():
        return clean
    return None


def main():
    if not INPUT_FILE.exists():
        print(f"ERROR: {INPUT_FILE} not found. Run extract_volunteers.py first.")
        sys.exit(1)

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    submissions = data["submissions"]
    selected = data["selected"]

    # Build set of selected WCA IDs
    selected_ids = set()
    for s in selected:
        if s.get("wca_id"):
            nid = normalize_wca_id_for_cs(s["wca_id"])
            if nid:
                selected_ids.add(nid)

    # Match submissions to selected
    matched = []
    for sub in submissions:
        nid = normalize_wca_id_for_cs(sub.get("wca_id"))
        if nid and nid in selected_ids:
            sub["_cs_id"] = nid
            matched.append(sub)

    print(f"Matched {len(matched)} submissions to selected volunteers")

    # Generate CompScript properties
    cs_lines = [
        '#include "../lib/_constants.cs"',
        "",
        "# ============================================================",
        "# SAC 2026 — Volunteer properties from form submissions",
        "# Generated by data/generate_import.py",
        "# ============================================================",
        "",
    ]

    # 1. Scramble capabilities per event
    event_ids = ["222", "333", "444", "555", "666", "777", "clock", "minx", "pyram", "skewb", "sq1"]
    for event in event_ids:
        ids = [m["_cs_id"] for m in matched if event in m.get("can_scramble", [])]
        if ids:
            cs_lines.append(f'# Can scramble {event}: {len(ids)} volunteers')
            cs_lines.append(f'SetProperty([{", ".join(ids)}], "can-scramble-{event}", true)')
            cs_lines.append("")

    # 2. Role preferences (normalized 1-10)
    cs_lines.append("# Role preferences (1-10 scale)")
    for m in matched:
        prefs = m.get("preferences", {})
        judge = int(prefs.get("judge", 0))
        scrambler = int(prefs.get("scrambler", 0))
        runner = int(prefs.get("runner", 0))
        data_entry = int(prefs.get("data_entry", 0))
        if judge > 0:
            cs_lines.append(f'SetProperty([{m["_cs_id"]}], "pref-judge", {judge})')
        if scrambler > 0:
            cs_lines.append(f'SetProperty([{m["_cs_id"]}], "pref-scrambler", {scrambler})')
        if runner > 0:
            cs_lines.append(f'SetProperty([{m["_cs_id"]}], "pref-runner", {runner})')
        if data_entry > 0:
            cs_lines.append(f'SetProperty([{m["_cs_id"]}], "pref-data-entry", {data_entry})')
    cs_lines.append("")

    # Write CompScript file
    with open(OUTPUT_CS, "w", encoding="utf-8") as f:
        f.write("\n".join(cs_lines) + "\n")
    print(f"Generated: {OUTPUT_CS}")

    # 3. Score taker report
    score_takers = sorted(
        [m for m in matched if m.get("preferences", {}).get("data_entry", 0) >= 8],
        key=lambda x: -x["preferences"]["data_entry"],
    )
    with open(OUTPUT_SCORE_TAKERS, "w", encoding="utf-8") as f:
        f.write("SAC 2026 — Score Taker Candidates (data_entry preference >= 8)\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"{'Name':<40} {'WCA ID':<12} {'DataEntry':>9} {'Judge':>6} {'Scramb':>6}\n")
        f.write("-" * 70 + "\n")
        for v in score_takers:
            p = v["preferences"]
            f.write(
                f"{v['name'][:39]:<40} {v.get('wca_id', 'N/A'):<12} "
                f"{p['data_entry']:>9.0f} {p['judge']:>6.0f} {p['scrambler']:>6.0f}\n"
            )
        f.write(f"\nTotal: {len(score_takers)} candidates\n")
    print(f"Generated: {OUTPUT_SCORE_TAKERS}")

    # 4. Scramble capability report
    with open(OUTPUT_SCRAMBLE, "w", encoding="utf-8") as f:
        f.write("SAC 2026 — Scramble Capabilities (Selected Volunteers)\n")
        f.write("=" * 70 + "\n\n")
        for event in event_ids:
            scramblers = [m for m in matched if event in m.get("can_scramble", [])]
            f.write(f"\n{event.upper()} ({len(scramblers)} volunteers can scramble):\n")
            for v in sorted(scramblers, key=lambda x: x["name"]):
                pref = int(v["preferences"].get("scrambler", 0))
                f.write(f"  {v['name'][:35]:<36} {v.get('wca_id', 'N/A'):<12} pref: {pref}/10\n")
        f.write(f"\n\nGenerated from {len(matched)} matched submissions\n")
    print(f"Generated: {OUTPUT_SCRAMBLE}")


if __name__ == "__main__":
    main()
